FROM node:20-alpine

WORKDIR /app

COPY web/package.json web/package-lock.json* ./
RUN npm install

COPY web ./

RUN npm run build

ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start"]
